from __future__ import annotations

import asyncio
import contextlib
import io
import logging
import pathlib
from datetime import timedelta
from typing import TYPE_CHECKING, Final

import discord
import imagehash
from discord.ext import commands
from PIL import Image

from modules.auto_mod import ModerationOutcome, escalate_member
from modules.dtypes import GuildId, is_guild_message

if TYPE_CHECKING:
    from modules.BotCore import BotCore
    from modules.ConfigDB import ConfigDB

log = logging.getLogger(__name__)

MIN_IMAGES: Final[int] = 2
# assume distances below ~10 are near-identical images
HASH_DISTANCE_THRESHOLD: Final[int] = 8
TIMEOUT_DURATION: Final[timedelta] = timedelta(hours=1)
# Skip decoding attachments larger than this
MAX_ATTACHMENT_BYTES: Final[int] = 100_000


def _load_scam_hashes() -> frozenset[imagehash.ImageHash]:
    """Load known scam hashes, one per line, generated by scripts/hash_scams.py."""
    with pathlib.Path("data/scam_hashes.txt").open() as f:
        return frozenset(imagehash.hex_to_hash(line.strip()) for line in f if line.strip())


KNOWN_SCAM_HASHES: Final[frozenset[imagehash.ImageHash]] = _load_scam_hashes()


class ScamImageCog(commands.Cog):
    """Cog for auto-moderating messages whose images match a known scam perceptual hash."""

    def __init__(self, bot: BotCore, *, config_db: ConfigDB) -> None:
        self.bot = bot
        self.config_db = config_db

    @commands.Cog.listener()
    async def on_message(self, message: discord.Message) -> None:
        if not is_guild_message(message) or message.author.bot or message.author.is_timed_out():
            return

        images = [a for a in message.attachments if a.content_type and a.content_type.startswith("image/")]
        if len(images) < MIN_IMAGES:
            return

        matched = await self._find_scam_match(images)
        if matched is None:
            return

        author_id = message.author.id

        with contextlib.suppress(discord.Forbidden):
            await message.delete()

        # Punishes the author in every mutual guild, not just where the scam image was posted
        # (each guild's Member is looked up separately, so "new member" is still evaluated per-guild).
        for guild in self.bot.guilds:
            member = guild.get_member(author_id)
            if member is not None:
                await self._moderate_member(member, guild, matched)

    async def _moderate_member(
        self,
        member: discord.Member,
        guild: discord.Guild,
        matched: discord.Attachment,
    ) -> None:
        outcome = await escalate_member(
            self.bot,
            member,
            guild,
            reason="known scam image",
            trigger="Scam image detected",
            timeout_duration=TIMEOUT_DURATION,
            warning_type="scamimage_no_permission",
        )
        if outcome is ModerationOutcome.FAILED:
            return

        action = (
            "Message deleted, new member kicked."
            if outcome is ModerationOutcome.KICKED
            else "Message deleted, member muted for 1 hour."
        )
        await self._log_scam_action(member, guild, matched, action=action)

    async def _find_scam_match(self, images: list[discord.Attachment]) -> discord.Attachment | None:
        """Download each attachment and return the first one matching a known scam hash."""
        if not KNOWN_SCAM_HASHES:
            return None

        for attachment in images:
            if attachment.size > MAX_ATTACHMENT_BYTES:
                continue

            try:
                data = await attachment.read()
                image_hash = await asyncio.to_thread(self._hash_image, data)
            except discord.HTTPException, OSError:
                log.exception("Failed to read/hash attachment %s", attachment.url)
                continue

            if image_hash is not None and any(image_hash - known <= HASH_DISTANCE_THRESHOLD for known in KNOWN_SCAM_HASHES):
                return attachment

        return None

    @staticmethod
    def _hash_image(data: bytes) -> imagehash.ImageHash | None:
        try:
            with Image.open(io.BytesIO(data)) as img:
                return imagehash.whash(img)
        except OSError:
            return None

    async def _log_scam_action(
        self,
        member: discord.Member,
        guild: discord.Guild,
        matched: discord.Attachment,
        *,
        action: str,
    ) -> None:
        """Record the auto-mod action in the guild's moderation log channel."""
        config = await self.config_db.get_guild_config(GuildId(guild.id))
        mod_channel_id = config.mod_log_channel_id
        if not mod_channel_id:
            return

        mod_channel = self.bot.get_channel(mod_channel_id)
        if not isinstance(mod_channel, discord.TextChannel):
            return

        embed = discord.Embed(
            title="Scam Image Detected",
            color=discord.Colour.dark_orange(),
            description=(
                f"**Target:** {member.mention} (`{member.id}`)\n**Action:** {action}\n**Matched image:** {matched.filename}"
            ),
            timestamp=discord.utils.utcnow(),
        )
        embed.set_author(name=f"{member.name} ({member.display_name})", icon_url=member.display_avatar)

        with contextlib.suppress(discord.Forbidden, discord.HTTPException):
            await mod_channel.send(embed=embed, allowed_mentions=None)


async def setup(bot: BotCore) -> None:
    """Add the ScamImageCog to the bot."""
    await bot.add_cog(ScamImageCog(bot=bot, config_db=bot.config_db))
